// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title ISP1Verifier
/// @notice Interface for the SP1 on-chain proof verifier.
interface ISP1Verifier {
    /// @notice Verifies a ZK proof generated by the SP1 prover.
    /// @param programVKey The verification key for the SP1 program.
    /// @param publicValues The public values committed in the proof.
    /// @param proofBytes The serialized proof bytes.
    function verifyProof(
        bytes32 programVKey,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external view;
}
